version: "3.7"

services:

  client:
    build: ./client
    container_name: client
    restart: always
    environment: 
      - APP_NAME=HE-Microservice-frontend
    expose: 
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"