version: "3.7"

services:

  server:
    build: ./server
    container_name: server
    restart: always
    environment: 
      - APP_NAME=HE-Microservice
    expose: 
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"