version: "3.7"

services:

  client:
    build: ./client
    container_name: client
    restart: always
    environment: 
      - APP_NAME=HE-Microservice-frontend
      - SECRET_KEY=random secret key
      - SQLALCHEMY_DATABASE_URI=sqlite:///../../database/database.db
    links:
      - db
    ports:
      - 80:80
    depends_on:
      - server
      
  server:
    build: ./server
    container_name: server
    restart: always
    environment: 
      - APP_NAME=HE-Microservice-backend
    ports:
      - 81:81
  